version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: study-tracker-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-study_tracker_dev}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - study-tracker-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-study_tracker_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: study-tracker-redis-dev
    restart: unless-stopped
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - study-tracker-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # 应用服务（开发模式）
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: study-tracker-app-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-study_tracker_dev}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dev-refresh-secret}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD:-Admin123!}
      TRUST_PROXY: false
      SESSION_SECURE_COOKIES: false
      SESSION_HTTP_ONLY: true
      SESSION_SAME_SITE: lax
      PASSWORD_MIN_LENGTH: 6
      PASSWORD_REQUIRE_UPPERCASE: false
      PASSWORD_REQUIRE_LOWERCASE: false
      PASSWORD_REQUIRE_NUMBERS: false
      PASSWORD_REQUIRE_SPECIAL_CHARS: false
      MAX_LOGIN_ATTEMPTS: 10
      LOCKOUT_DURATION_MINUTES: 5
      MAX_FILE_SIZE: 10485760
      ALLOWED_FILE_TYPES: image/jpeg,image/png,image/gif,application/pdf
      CORS_ORIGIN: http://localhost:3001
      CORS_CREDENTIALS: true
      LOG_LEVEL: debug
      LOG_SECURITY_EVENTS: true
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_dev_data:/app/uploads
      - ./logs:/app/logs
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - study-tracker-dev-network
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  uploads_dev_data:
    driver: local

networks:
  study-tracker-dev-network:
    driver: bridge 