version: '3.8'

services:
  study-tracker:
    build: .
    container_name: study-tracker
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - study-tracker-network

  # Nginx反向代理（可选，用于SSL终止）
  nginx:
    image: nginx:alpine
    container_name: study-tracker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - study-tracker
    restart: unless-stopped
    networks:
      - study-tracker-network

networks:
  study-tracker-network:
    driver: bridge

volumes:
  study-tracker-data: 