version: '2.4'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: study-tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: study_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: study-tracker-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  # 应用服务（本地构建）
  app:
    build: .
    container_name: study-tracker-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: study_tracker
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-jwt-key-change-this-in-production
      DEFAULT_ADMIN_PASSWORD: Admin123!
    volumes:
      - uploads_data:/app/uploads
      - ./logs:/app/logs
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
  uploads_data: 