name = "study-tracker"
main = "server.js"
compatibility_date = "2024-01-01"

[env.production]
name = "study-tracker-prod"

[env.staging]
name = "study-tracker-staging"

[build]
command = "npm install"

[[env.production.routes]]
pattern = "api/*"
script = "server.js"

[[env.staging.routes]]
pattern = "api/*"
script = "server.js" 